-- PostgreSQL 16+; safe to run again. Existing data is preserved.
CREATE TABLE IF NOT EXISTS app_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255),
  role VARCHAR(255),
  active BOOLEAN,
  capacity INTEGER);

CREATE TABLE IF NOT EXISTS offering (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,
  name VARCHAR(255),
  kind VARCHAR(255),
  description VARCHAR(10000),
  deliverables VARCHAR(10000),
  price NUMERIC(38,2),
  status VARCHAR(255),
  feedback VARCHAR(10000));

CREATE TABLE IF NOT EXISTS quotation (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,
  customer_id BIGINT,
  title VARCHAR(255),
  requirements VARCHAR(10000),
  lines VARCHAR(10000),
  total NUMERIC(38,2),
  status VARCHAR(255),
  feedback VARCHAR(10000),
  FOREIGN KEY (customer_id) REFERENCES app_user(id));

CREATE TABLE IF NOT EXISTS project (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,
  quotation_id BIGINT,
  customer_id BIGINT,
  title VARCHAR(255),
  status VARCHAR(255),
  progress INTEGER,
  prototype_approved BOOLEAN,
  client_approved BOOLEAN,
  UNIQUE (quotation_id),
  FOREIGN KEY (quotation_id) REFERENCES quotation(id),
  FOREIGN KEY (customer_id) REFERENCES app_user(id));

CREATE TABLE IF NOT EXISTS invoice (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,
  project_id BIGINT,
  customer_id BIGINT,
  amount NUMERIC(38,2),
  billing_name VARCHAR(255),
  billing_address VARCHAR(255),
  status VARCHAR(255),
  feedback VARCHAR(10000),
  payment_reference VARCHAR(255),
  UNIQUE (project_id),
  FOREIGN KEY (project_id) REFERENCES project(id),
  FOREIGN KEY (customer_id) REFERENCES app_user(id));

CREATE TABLE IF NOT EXISTS conversation (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,
  customer_id BIGINT,
  subject VARCHAR(255),
  message VARCHAR(10000),
  reply VARCHAR(10000),
  kind VARCHAR(255),
  appointment_at VARCHAR(255),
  status VARCHAR(255),
  FOREIGN KEY (customer_id) REFERENCES app_user(id));

CREATE TABLE IF NOT EXISTS assignment (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,project_id BIGINT NOT NULL REFERENCES project(id),designer_id BIGINT NOT NULL REFERENCES app_user(id),UNIQUE(project_id,designer_id));
CREATE TABLE IF NOT EXISTS project_feedback (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,project_id BIGINT NOT NULL REFERENCES project(id),author_role VARCHAR(255),message VARCHAR(10000),approved BOOLEAN);
CREATE TABLE IF NOT EXISTS asset (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,project_id BIGINT NOT NULL REFERENCES project(id),kind VARCHAR(255),original_name VARCHAR(255),storage_name VARCHAR(255),content_type VARCHAR(255));
CREATE TABLE IF NOT EXISTS outbox_mail (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT, created_at TIMESTAMP WITH TIME ZONE,recipient VARCHAR(255),subject VARCHAR(255),body VARCHAR(20000),status VARCHAR(255));

-- Safe upgrade: preserves accounts, quotations, projects and payments.
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE quotation ADD COLUMN IF NOT EXISTS additional_amount NUMERIC(38,2) DEFAULT 0;
ALTER TABLE quotation ADD COLUMN IF NOT EXISTS additional_description VARCHAR(10000);
UPDATE app_user SET role = 'SERVICE_STAFF' WHERE role = 'SERVICES';
UPDATE app_user SET role = 'MARKETING_MANAGER' WHERE role = 'MARKETING';
UPDATE app_user SET role = 'QUOTATION_STAFF' WHERE role = 'QUOTES';
UPDATE app_user SET role = 'FINANCE_MANAGER' WHERE role IN ('FINANCE_QUOTES', 'FINANCE_PAYMENTS');
UPDATE app_user SET role = 'PROJECT_MANAGER' WHERE role = 'DIRECTOR';
UPDATE app_user SET role = 'FINANCE_STAFF' WHERE role = 'PAYMENTS';
UPDATE app_user SET role = 'COMMUNICATION_STAFF' WHERE role = 'COMMUNICATIONS';
UPDATE app_user SET role = 'CUSTOMER_RELATIONS_OFFICER' WHERE role = 'CRO';
UPDATE project_feedback SET author_role = 'PROJECT_MANAGER' WHERE author_role = 'DIRECTOR';

-- Invoice review and payment receipt metadata; additive migration.
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS project_title VARCHAR(255);
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255);
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS payment_method VARCHAR(255);
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP WITH TIME ZONE;
-- Legacy SENT records already had verified payment before invoice delivery.
UPDATE invoice SET status = 'PAID' WHERE status IN ('SENT', 'REVIEW', 'APPROVED', 'CHANGES') AND payment_reference IS NOT NULL;
UPDATE invoice SET status = 'GENERATED' WHERE status = 'APPROVED';
UPDATE invoice SET project_title = (SELECT title FROM project WHERE project.id = invoice.project_id) WHERE project_title IS NULL;
UPDATE invoice SET customer_name = (SELECT name FROM app_user WHERE app_user.id = invoice.customer_id) WHERE customer_name IS NULL;
UPDATE invoice SET customer_email = (SELECT email FROM app_user WHERE app_user.id = invoice.customer_id) WHERE customer_email IS NULL;

-- Preserve each conversation reply in chronological order.
CREATE TABLE IF NOT EXISTS conversation_reply (
  conversation_id BIGINT NOT NULL REFERENCES conversation(id),
  reply_order INTEGER NOT NULL,
  author_id BIGINT,
  author_name VARCHAR(255),
  author_role VARCHAR(255),
  body VARCHAR(10000),
  sent_at TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (conversation_id, reply_order)
);
UPDATE conversation SET status = 'SOLVED' WHERE status = 'CLOSED';

ALTER TABLE app_user ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS contact_no VARCHAR(255);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS sex VARCHAR(255);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS contact_no VARCHAR(255);
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
