/* Workflow lifecycle controls for the interactive prototype. */
const archive=[];
const modules={users:{label:'User accounts',roles:['admin'],list:users},catalog:{label:'Services, packages & promotions',roles:['services','marketing'],list:catalog},quotes:{label:'Quotations & briefs',roles:['quotes','finance_quotes','customer'],list:quotes},projects:{label:'Projects',roles:['director'],list:projects},assets:{label:'Design assets',roles:['designer'],list:null},payments:{label:'Payment requests',roles:['payments','finance_payments'],list:paymentRequests},invoices:{label:'Invoices',roles:['payments','finance_payments'],list:invoices},threads:{label:'Conversations',roles:['communications','cro','customer'],list:threads},appointments:{label:'Consultations',roles:['cro','customer'],list:appointments}};
const recordTitle=r=>r.name||r.title||r.topic||r.id;
const allRecords=type=>[...modules[type].list,...archive.filter(a=>a.type===type).map(a=>a.record)];
// Deleted accounts retain inactive identity records for linked project history.
let manageType='',showArchive=false;
Object.entries(roles).forEach(([key,r])=>r.pages.push(['manage','Manage records']));
projects.forEach(p=>p.agreedTotal??=quotes.find(q=>q.id===p.quoteId)?total(quotes.find(q=>q.id===p.quoteId)):p.id==='P-101'?185000:0);
paymentRequests.push({id:'PAY-102',projectId:'P-101',clientId:'u12',title:'Luma — final balance',amount:92500,status:'Unpaid',date:today()});
function releaseState(p){
 const requests=allRecords('payments').filter(r=>r.projectId===p.id&&r.clientId===p.clientId&&r.status!=='Cancelled');
 const matched=requests.map(r=>({request:r,transaction:transactions.find(t=>t.requestId===r.id&&t.clientId===p.clientId&&t.status==='Succeeded'&&t.verified===true&&t.amount===r.amount)}));
 const paid=matched.reduce((sum,m)=>sum+(m.request.status==='Paid'&&m.transaction?m.transaction.amount:0),0);
 const required=Number(p.agreedTotal||requests.reduce((sum,r)=>sum+r.amount,0));
 const paymentsReady=required>0&&requests.length>0&&paid>=required&&matched.every(m=>m.request.status==='Paid'&&m.transaction);
 const invoicesReady=paymentsReady&&matched.every(m=>allRecords('invoices').some(i=>i.transactionId===m.transaction.id&&i.clientId===p.clientId&&i.amount===m.transaction.amount&&i.status==='Sent to client'));
 return {allowed:paymentsReady&&invoicesReady,paymentsReady,invoicesReady,paid,required};
}
function deliverableSection(p){if(!p.deliverables?.length)return '';const state=releaseState(p);return `<h3 class="subheading">Original files</h3>${role==='customer'?`<div class="release-panel ${state.allowed?'released':''}"><span class="tileicon">${icon(state.allowed?'check':'shield')}</span><div><strong>${state.allowed?'Your originals are ready.':'Original downloads are locked.'}</strong><p>${state.allowed?'Payment verified and approved invoices delivered.':'Preview the design above. Originals unlock after full payment verification and invoice delivery.'}</p><div class="release-steps"><span>${state.paymentsReady?'✓':'○'} Full payment verified · ${money(state.paid)} / ${money(state.required)}</span><span>${state.invoicesReady?'✓':'○'} Correct invoices approved & delivered</span></div></div></div>`:''}<div class="queue-list">${p.deliverables.map((d,i)=>`<div class="queuerow"><div class="grow"><strong>${esc(d.name)}</strong><small>${esc(d.note)} · ${esc(d.date)}</small></div>${role!=='customer'||state.allowed?button('Download original ↧','original',p.id+'|'+i,'primary'):'<span class="locked-label">'+icon('shield')+' Awaiting release</span>'}</div>`).join('')}</div>`;}
function allowedTypes(){return Object.entries(modules).filter(([k,m])=>m.roles.includes(role)).map(([k])=>k);}
function recordsFor(type){if(type==='assets')return visibleProjects().flatMap(p=>[...(p.deliverables||[]).map((d,i)=>({id:p.id+'|final|'+i,name:d.name,status:'Final asset',project:p.id})),...p.prototypes.map((v,i)=>({id:p.id+'|prototype|'+i,name:p.title+' · Prototype V'+v.version,status:v.status,project:p.id}))]);let list=modules[type].list.filter(r=>!r.deleted);if(role==='customer')list=list.filter(r=>r.clientId===userId&&(type!=='threads'||r.type==='Client'));return list;}
function editableRecord(type,r){if(type==='users')return role==='admin';if(type==='catalog')return role==='services'&&r.status!=='Pending review';if(type==='quotes')return role==='customer'?r.clientId===userId&&r.status==='Requested':role==='quotes'&&!['Accepted','Sent to client','Finance review'].includes(r.status);if(type==='projects')return role==='director'&&r.status!=='Completed';if(type==='payments')return can('payments','finance_payments')&&r.status==='Unpaid';if(type==='invoices')return (role==='finance_payments'&&['Finance review','Changes requested','Approved','Sent to client'].includes(r.status)||role==='payments'&&['Finance review','Changes requested'].includes(r.status));if(type==='threads')return can('communications','cro')||r.clientId===userId;if(type==='appointments')return role==='cro'||r.clientId===userId&&r.status==='Requested';if(type==='assets')return role==='designer';return false;}
function removalLabel(type,r){if(type==='users')return 'Delete account';if(type==='invoices'||type==='projects'||type==='quotes'&&['Accepted','Sent to client'].includes(r.status)||type==='payments'&&r.status==='Paid')return 'Archive';if(type==='threads')return 'Archive conversation';return 'Delete';}
function mayRemove(type,r){if(type==='users')return role==='admin'&&r.id!==userId&&!r.deleted;if(type==='catalog')return can('services','marketing');if(type==='quotes')return role==='quotes'&&r.status!=='Finance review'||role==='customer'&&r.clientId===userId&&r.status==='Requested';if(type==='projects')return role==='director';if(type==='payments')return can('payments','finance_payments');if(type==='invoices')return can('payments','finance_payments');if(type==='threads')return can('communications','cro')||role==='customer'&&r.clientId===userId;if(type==='appointments')return role==='cro'||role==='customer'&&r.clientId===userId&&['Requested','Cancelled'].includes(r.status);if(type==='assets')return role==='designer'&&r.status!=='Approved for final';return false;}
function createAction(type){return {users:['Create account +','invite'],catalog:role==='services'?['Create offering +','catalognew']:null,quotes:role==='customer'?['Create project brief +','go-catalogue']:role==='quotes'?['Create quotation +','newquote']:null,projects:['Create from accepted quotation +','projectcreate'],assets:['Upload design asset +','assetcreate'],payments:['Create payment request +','newpayment'],invoices:['Create from verified payment +','newinvoice'],threads:['New conversation +','newthread'],appointments:['Create consultation +','newconsult']}[type];}
const basePageView=pageView;
pageView=function(){return page==='manage'?managePage():basePageView();};
function managePage(){const types=allowedTypes();if(!types.includes(manageType))manageType=types[0];const type=manageType,m=modules[type],create=createAction(type);const rows=showArchive?archive.filter(a=>a.type===type&&(role!=='customer'||a.record.clientId===userId)).map(a=>a.record):recordsFor(type);return head('Keep the details in good shape.','Create, view, and update records. Deletions and archives are recorded in the activity trail.',create&&!showArchive?create[1]:'',create?.[0]||'')+`<div class="filters">${types.map(t=>`<button class="filter ${type===t?'active':''}" data-act="managetype" data-id="${t}">${modules[t].label}</button>`).join('')}</div><div class="record-toolbar"><strong>${m.label}</strong>${button(showArchive?'Show active records':'Open archive','archivetoggle')}</div>${section(showArchive?'Archived records':'Active records',rows.length?`<div class="tablewrap"><table><thead><tr><th>RECORD</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(recordTitle(r))}</strong><small>${esc(r.id)}${r.email?' · '+esc(r.email):''}</small></td><td>${status(type==='users'?(r.active?'Active':'Suspended'):r.status||'Active')}</td><td><div class="record-actions">${showArchive?button('Restore','recordrestore',type+'|'+r.id):button('View','recordview',type+'|'+r.id)+(editableRecord(type,r)?button('Edit','recordedit',type+'|'+r.id):'')+(mayRemove(type,r)?button(removalLabel(type,r),'recordremove',type+'|'+r.id,'danger-quiet'):'')}</div></td></tr>`).join('')}</tbody></table></div>`:empty(showArchive?'Nothing in the archive.':'No records yet.'))}`;}
function findRecord(type,id){return recordsFor(type).find(r=>r.id===id);}
function requestRemove(type,id){const r=findRecord(type,id);if(!r||!mayRemove(type,r))return;let reason=type==='users'?'The account will lose access. Existing projects, invoices, and activity retain the person’s reference.':type==='invoices'?'The paid invoice is archived, not erased. Payment verification and financial history remain intact.':type==='projects'?'The project leaves active views. Related financial records remain intact. Restore it from the archive when needed.':'This record leaves active views and can be restored from the archive.';if(type==='assets')reason='This file will be removed from the project. Existing review decisions remain in the activity trail.';modal(removalLabel(type,r)+'?',`<p><strong>${esc(recordTitle(r))}</strong></p><p>${reason}</p><form data-form="remove-record" data-type="${type}" data-id="${esc(id)}">${area('Reason','reason','',true)}<div class="actions"><button type="button" class="btn" data-act="close">Keep record</button><button class="btn danger">Confirm ${type==='users'?'account deletion':removalLabel(type,r).toLowerCase()}</button></div></form>`);}
function editRecord(type,id){const r=findRecord(type,id);if(!r||!editableRecord(type,r))return;
 if(type==='users'){editUser(id);return;}if(type==='catalog'){if(r.status==='Published'){r.status='Draft';hist(r,'Published offering withdrawn for employee revision; new approval required');}catalogEditor(id);return;}
 if(type==='quotes'){if(role==='customer'){modal('Update your project brief.',`<form data-form="edit-brief" data-id="${id}">${field('Project title','title',r.title,'text','required')}${area('Requirements','brief',r.brief,true)}${area('Additional preferences','notes',r.notes)}<button class="btn primary">Save brief</button></form>`);}else{if(r.status==='Approved'){r.status='Changes requested';hist(r,'Employee reopened quotation; finance approval reset');}quoteDetail(id);}return;}
 if(type==='projects'){assignment(id,true);return;}if(type==='payments'){paymentEditor(id);return;}
 if(type==='invoices'){modal('Correct invoice details.',`<p>Saving changes sends this invoice back through finance review. The paid amount remains unchanged.</p><form data-form="edit-invoice" data-id="${id}">${field('Billing name','billTo',r.billTo,'text','required')}${field('Billing email','email',r.email,'email','required')}${area('Billing address','address',r.address,true)}${area('Correction note','note','',true)}<button class="btn primary">Save & request approval</button></form>`);return;}
 if(type==='threads'){modal('Update conversation.',`<form data-form="edit-thread" data-id="${id}">${field('Title','name',r.name,'text','required')}${field('Subject','subject',r.subject,'text','required')}${role!=='customer'?select('Assigned officer','owner',users.filter(u=>u.active&&u.roles.some(x=>['communications','cro'].includes(x))).map(u=>[u.id,u.name]),r.owner):''}<button class="btn primary">Save conversation</button></form>`);return;}
 if(type==='appointments'){if(role==='cro'){appointmentDialog(id);return;}modal('Update consultation request.',`<form data-form="edit-appointment" data-id="${id}">${field('Topic','topic',r.topic,'text','required')}${field('Date','date',r.date,'date',`required min="${today()}"`)}${select('Time · Sri Lanka','time',['09:00','11:00','14:00','16:00'],r.time)}${area('Context','note',r.note)}<button class="btn primary">Save request</button></form>`);return;}
 if(type==='assets'){const [pid,kind,index]=id.split('|'),p=visibleProjects().find(p=>p.id===pid),asset=(kind==='final'?p.deliverables:p.prototypes)[Number(index)];modal('Update asset notes.',`<form data-form="edit-asset" data-id="${esc(id)}">${area('Notes','note',kind==='final'?asset.note:asset.caption,true)}<button class="btn primary">Save notes</button></form>`);}
}
function paymentEditor(id){if(!guard('payments','finance_payments'))return;const p=paymentRequests.find(x=>x.id===id);modal(p?'Edit payment request.':'Create a payment request.',`<p>Only unpaid requests can be edited. Recorded transactions and verified amounts cannot be changed.</p><form data-form="payment-request" data-id="${id||''}">${select('Project','project',projects.map(p=>[p.id,p.title]),p?.projectId||projects[0]?.id)}${field('Description','title',p?.title||'','text','required')}${field('Amount (LKR)','amount',p?.amount||'','number','min="0.01" step="0.01" required')}<button class="btn primary">Save payment request</button></form>`);}
function newQuoteDialog(){if(!guard('quotes'))return;modal('Create a quotation.',`<form data-form="new-quote">${select('Customer','client',users.filter(u=>u.active&&u.roles.includes('customer')).map(u=>[u.id,u.name]))}${field('Project title','title','','text','required')}${area('Client brief','brief','',true)}${field('First deliverable','item','','text','required')}${field('Unit price (LKR)','price','','number','min="0" step="0.01" required')}<button class="btn primary">Create draft quotation</button></form>`);}
function newInvoiceDialog(){if(!guard('payments','finance_payments'))return;const available=transactions.filter(t=>t.status==='Succeeded'&&t.verified&&!allRecords('invoices').some(i=>i.transactionId===t.id));modal('Create an invoice from a payment.',available.length?`<form data-form="new-invoice">${select('Verified transaction','transaction',available.map(t=>[t.id,t.id+' · '+money(t.amount)]))}${field('Billing name','billTo','','text','required')}${field('Billing email','email','','email','required')}${area('Billing address','address','',true)}<button class="btn primary">Generate & submit for approval</button></form>`:empty('Every verified payment has an invoice.','New invoices are generated automatically after successful checkout. Archive and restore existing records without creating duplicates.'));}
function emailHTML(type,r){const c=currentClient(r.clientId),lines=type==='quote'?r.lines:[{name:r.title,qty:1,price:r.amount,discount:0}];return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(r.id)}</title><style>body{font:15px Arial,sans-serif;color:#203429;max-width:800px;margin:40px auto;padding:25px}header{border-bottom:3px solid #203429;display:flex;justify-content:space-between}h1{font-size:34px}table{width:100%;border-collapse:collapse;margin:25px 0}td,th{text-align:left;border-bottom:1px solid #ddd;padding:12px}th{background:#edf2e8}footer{margin-top:40px;border-top:1px solid #ddd;padding-top:15px}</style></head><body><header><div><h1>↗ ${esc(agency.name)}</h1><p>${esc(agency.address)}<br>${esc(agency.email)} · ${esc(agency.phone)}</p></div><div><h2>${type==='quote'?'QUOTATION':'INVOICE'}</h2><p>${esc(r.id)} · V${r.revision}<br>${esc(r.date)}</p></div></header><h3>Prepared for ${esc(type==='invoice'?r.billTo:c.company||c.name)}</h3><p>${esc(type==='invoice'?r.email:c.email)}${type==='invoice'?'<br>'+esc(r.address):''}</p><h2>${esc(r.title)}</h2><table><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Discount</th><th>Amount</th></tr></thead><tbody>${lines.map(l=>`<tr><td>${esc(l.name)}</td><td>${l.qty}</td><td>${money(l.price)}</td><td>${l.discount||0}%</td><td>${money(l.qty*l.price*(1-(l.discount||0)/100))}</td></tr>`).join('')}</tbody></table><h2>Total: ${money(type==='quote'?total(r):r.amount)}</h2><p>${esc(type==='quote'?r.terms:'Payment reference: '+r.transactionId)}</p><p>${esc(r.delivery||'')}</p><footer>AXIOM Studio · Sample document from an interactive prototype. No real payment was processed.</footer></body></html>`;}
function emailComposer(type,id){if(!guard(type==='quote'?'finance_quotes':'finance_payments'))return;const r=(type==='quote'?quotes:invoices).find(x=>x.id===id);if(!r||!['Approved','Sent to client'].includes(r.status))return;const msg=outbox.find(m=>m.type===type&&m.ref===id);modal('Deliver in the portal. Send by email.',`<div class="delivery-channels"><div>${icon('check')}<strong>Customer portal</strong><small>${r.status==='Sent to client'?'Document delivered':'Ready for delivery'}</small></div><div>${icon('doc')}<strong>Email attachment</strong><small>Draft ready for your mail app</small></div></div><p>Open an email draft with the ${type==='quote'?'quotation':'invoice'} attached as an HTML document. You can print it to PDF. Your email app sends the message; this site cannot confirm delivery.</p><form data-form="email-draft" data-type="${type}" data-id="${id}">${field('To','to',msg?.to||(type==='invoice'?r.email:currentClient(r.clientId).email),'email','required')}${field('Subject','subject',msg?.subject||'Your AXIOM '+type+' · '+id,'text','required')}${area('Message','body',msg?.body||'Please find your document attached.',true)}<div class="attachment">${icon('doc')} ${id}.html · full document attached</div><div class="actions"><button class="btn primary" name="emailaction" value="eml">Download email draft (.eml)</button><button class="btn" name="emailaction" value="mailto">Open email app</button></div><p class="smallcopy muted">The .eml draft includes the attachment. “Open email app” prepares text only; attach the document manually. Automatic sending requires a connected mail service.</p></form>`,true);}
function saveBlob(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function base64utf8(s){const bytes=new TextEncoder().encode(s);let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).match(/.{1,76}/g).join('\r\n');}
function emlDraft(msg,type,r){const boundary='axiom_'+r.id.replace(/[^a-z0-9]/gi,'_');return ['To: '+msg.to.replace(/[\r\n]/g,''),'Subject: =?UTF-8?B?'+base64utf8(msg.subject).replace(/\r\n/g,'')+'?=','MIME-Version: 1.0','X-Unsent: 1','Content-Type: multipart/mixed; boundary="'+boundary+'"','','--'+boundary,'Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',base64utf8(msg.body),'--'+boundary,'Content-Type: text/html; charset=UTF-8; name="'+r.id+'.html"','Content-Disposition: attachment; filename="'+r.id+'.html"','Content-Transfer-Encoding: base64','',base64utf8(emailHTML(type,r)),'--'+boundary+'--',''].join('\r\n');}
const baseOutbox=outboxPage;
outboxPage=function(){const type=role==='finance_quotes'?'quote':'invoice';return head('A document. Two delivery channels.','Publish approved documents to the client portal and prepare an email with the document attached.')+section('Approved documents',`<div class="queue-list">${(type==='quote'?quotes:invoices).filter(r=>['Approved','Sent to client'].includes(r.status)).map(r=>`<div class="queuerow"><span class="tileicon">${icon('doc')}</span><div class="grow"><strong>${r.id} · ${esc(r.title)}</strong><small>Portal: ${r.status==='Sent to client'?'Delivered':'Awaiting delivery'} · Email: ${esc(outbox.find(m=>m.ref===r.id)?.emailStatus||'Not prepared')}</small></div>${button(r.status==='Approved'?'Deliver & prepare email':'Email document',r.status==='Approved'?(type==='quote'?'quotesend':'invoicesend'):'emailcompose',r.status==='Approved'?r.id:type+'|'+r.id,'primary')}</div>`).join('')||empty('No approved documents yet.')}</div>`)+`<div class="notice">Email sending is manual in this prototype. Download a draft with its attachment or open your email app; the site never reports these as sent automatically.</div>`;};
const baseAct=act;
act=function(action,id=''){
 if(action==='managetype'){manageType=id;showArchive=false;render();return;}if(action==='archivetoggle'){showArchive=!showArchive;render();return;}
 if(action==='original'){const [pid,index]=id.split('|'),p=visibleProjects().find(p=>p.id===pid),d=p?.deliverables?.[Number(index)];if(!d)return;if(role==='customer'&&!releaseState(p).allowed){toast('Original files are locked until payment verification and invoice delivery.');return;}const a=document.createElement('a');a.href=d.url;a.download=d.name;document.body.appendChild(a);a.click();a.remove();return;}
 if(action.startsWith('record')){const [type,...parts]=id.split('|'),key=parts.join('|');if(!allowedTypes().includes(type))return;const r=findRecord(type,key);if(action==='recordremove'){requestRemove(type,key);return;}if(action==='recordedit'){editRecord(type,key);return;}if(action==='recordrestore'){const a=archive.find(a=>a.type===type&&a.record.id===key);if(!a||role==='customer'&&a.record.clientId!==userId)return;if(type==='users'){a.record.deleted=false;a.record.active=a.wasActive;}else{if(type==='catalog')a.record.status='Draft';if(type==='payments'&&a.record.status!=='Paid'){const p=projects.find(p=>p.id===a.record.projectId),sum=allRecords('payments').filter(r=>r.id!==key&&r.projectId===a.record.projectId&&r.status!=='Cancelled').reduce((n,r)=>n+r.amount,0);if(p&&sum+a.record.amount>p.agreedTotal){toast('Restoring this request would exceed the project total. Adjust the unpaid requests first.');return;}a.record.status='Unpaid';}modules[type].list.push(a.record);}archive.splice(archive.indexOf(a),1);audit.unshift({text:'Restored '+type+' '+key,at:time(),role:roles[role].name});render();toast('Record restored'+(type==='catalog'?' as a draft for approval':''));return;}if(action==='recordview'&&r){if(type==='catalog')catalogDetail(key);else if(type==='quotes')quoteDetail(key);else if(type==='projects')projectDetail(key);else if(type==='invoices')invoiceDetail(key);else if(type==='users')editUser(key);else if(type==='threads'){activeThread=key;go('messages');}else if(type==='appointments'){role==='cro'?appointmentDialog(key):modal(esc(r.topic),`<p>${r.date} · ${r.time}</p>${status(r.status)}<p>${esc(r.note)}</p>`);}else if(type==='assets')projectDetail(r.project);else modal(esc(recordTitle(r)),`<p>${r.id} · ${r.date}</p><div class="detailprice">${money(r.amount)}</div>${status(r.status)}`);return;}}
 if(action==='newpayment'){paymentEditor();return;}if(action==='newquote'){newQuoteDialog();return;}if(action==='newinvoice'){newInvoiceDialog();return;}
 if(action==='projectcreate'){const qs=quotes.filter(q=>q.status==='Accepted'&&!projects.some(p=>p.quoteId===q.id));modal('Begin with an accepted quotation.',qs.length?`<div class="queue-list">${qs.map(q=>`<div class="queuerow"><div class="grow"><strong>${esc(q.title)}</strong><small>${q.id}</small></div>${button('Create project','startproject',q.id,'primary')}</div>`).join('')}</div>`:empty('No accepted quotations waiting.','Clients must accept a finance-approved quotation before project creation.'));return;}
 if(action==='assetcreate'){modal('Choose your project.',`<div class="queue-list">${visibleProjects().map(p=>`<div class="queuerow"><div class="grow"><strong>${esc(p.title)}</strong></div>${button('Upload prototype','upload',p.id)}</div>`).join('')}</div>`);return;}
 if(action==='newconsult'){if(role==='customer'){consult();return;}modal('Create a consultation.',`<form data-form="staff-consult">${select('Customer','client',users.filter(u=>u.active&&u.roles.includes('customer')).map(u=>[u.id,u.name]))}${field('Topic','topic','','text','required')}${field('Date','date','','date',`required min="${today()}"`)}${select('Time · Sri Lanka','time',['09:00','11:00','14:00','16:00'])}${area('Notes','note')}<button class="btn primary">Create consultation</button></form>`);return;}
 if(action==='emailcompose'){const [type,key]=id.split('|');emailComposer(type,key);return;}
 if(action==='quotesend'||action==='invoicesend'){baseAct(action,id);const type=action==='quotesend'?'quote':'invoice',r=(type==='quote'?quotes:invoices).find(x=>x.id===id);if(r?.status==='Sent to client'){const m=outbox.find(m=>m.ref===id&&m.type===type);if(m)m.emailStatus='Draft prepared';emailComposer(type,id);toast('Delivered to the portal. Email draft is ready for your mail app.');}return;}
 baseAct(action,id);
};
const baseSubmitForm=submitForm;
submitForm=function(form,submitter){const kind=form.dataset.form,id=form.dataset.id,f=new FormData(form),get=n=>String(f.get(n)||'').trim();let done=true;
 if(kind==='email-draft'){const type=form.dataset.type;if(!guard(type==='quote'?'finance_quotes':'finance_payments'))return;const r=(type==='quote'?quotes:invoices).find(x=>x.id===id);if(!r||!['Approved','Sent to client'].includes(r.status))return;const msg=outbox.find(m=>m.type===type&&m.ref===id)||{type,ref:id,at:time()};Object.assign(msg,{to:get('to'),subject:get('subject'),body:get('body'),emailStatus:submitter?.value==='mailto'?'Opened in email app · delivery unconfirmed':'Draft downloaded · delivery unconfirmed'});if(!outbox.includes(msg))outbox.unshift(msg);if(submitter?.value==='mailto'){const a=document.createElement('a');a.href='mailto:'+encodeURIComponent(msg.to)+'?subject='+encodeURIComponent(msg.subject)+'&body='+encodeURIComponent(msg.body+'\n\nDocument: '+r.id+'\nPlease attach the quotation/invoice document before sending.');a.click();}else saveBlob(r.id+'.eml',new Blob([emlDraft(msg,type,r)],{type:'message/rfc822'}));hist(r,'Email draft prepared for '+msg.to+'; sending and delivery not confirmed');toast('Email draft prepared. Send it from your email app.');return;}
 else if(kind==='remove-record'){const type=form.dataset.type,r=findRecord(type,id);if(!r||!mayRemove(type,r)||!get('reason'))return;if(type==='assets'){const [pid,k,index]=id.split('|'),p=visibleProjects().find(p=>p.id===pid);if(!p)return;const list=k==='final'?p.deliverables:p.prototypes;list.splice(Number(index),1);hist(p,'Designer removed '+recordTitle(r)+': '+get('reason'));}else if(type==='users'){archive.push({type,record:r,wasActive:r.active});r.deleted=true;r.active=false;}else{archive.push({type,record:r});if(type==='payments'&&r.status==='Unpaid')r.status='Cancelled';modules[type].list.splice(modules[type].list.indexOf(r),1);if(type==='catalog')cart=cart.filter(c=>c.id!==id);}audit.unshift({text:removalLabel(type,r)+' '+id+': '+get('reason'),at:time(),role:roles[role].name});}
 else if(kind==='edit-brief'){const q=findRecord('quotes',id);if(!q||!editableRecord('quotes',q))return;Object.assign(q,{title:get('title'),brief:get('brief'),notes:get('notes')});hist(q,'Customer updated the submitted brief');}
 else if(kind==='payment-request'){if(!guard('payments','finance_payments'))return;const existing=paymentRequests.find(r=>r.id===id),p=projects.find(p=>p.id===get('project')),amount=Number(get('amount'));if(!p||amount<=0||!Number.isFinite(amount)||existing&&existing.status!=='Unpaid')return;const other=allRecords('payments').filter(r=>r.projectId===p.id&&r.id!==id&&r.status!=='Cancelled').reduce((sum,r)=>sum+r.amount,0);if(other+amount>p.agreedTotal){toast('Payment requests cannot exceed the agreed project total. Edit an unpaid request or update the agreed scope first.');return;}const r=existing||{id:uid('PAY'),date:today(),status:'Unpaid'};Object.assign(r,{projectId:p.id,clientId:p.clientId,title:get('title'),amount});if(!existing)paymentRequests.push(r);audit.unshift({text:'Saved payment request '+r.id,at:time(),role:roles[role].name});}
 else if(kind==='new-quote'){if(!guard('quotes'))return;const price=Number(get('price'));if(price<0||!Number.isFinite(price))return;const q={id:uid('QT-2026'),clientId:get('client'),title:get('title'),date:today(),status:'Draft',revision:0,estimate:price,lines:[{id:uid('LINE'),name:get('item'),qty:1,price,discount:0}],brief:get('brief'),notes:'',terms:agency.terms,feedback:[],history:[]};quotes.push(q);hist(q,'Employee created draft quotation');}
 else if(kind==='edit-invoice'){const r=findRecord('invoices',id);if(!r||!editableRecord('invoices',r))return;Object.assign(r,{billTo:get('billTo'),email:get('email'),address:get('address'),status:'Finance review',revision:r.revision+1});r.feedback.push({by:roles[role].name,text:get('note')});hist(r,'Invoice corrected; finance approval required again');}
 else if(kind==='new-invoice'){if(!guard('payments','finance_payments'))return;const t=transactions.find(t=>t.id===get('transaction')&&t.verified&&t.status==='Succeeded');if(!t||allRecords('invoices').some(i=>i.transactionId===t.id)){toast('This payment already has an invoice.');return;}const i={id:uid('INV-2026'),transactionId:t.id,clientId:t.clientId,title:t.title,date:today(),amount:t.amount,billTo:get('billTo'),email:get('email'),address:get('address'),status:'Finance review',revision:1,feedback:[],history:[]};invoices.push(i);hist(i,'Invoice created from verified payment and submitted for finance approval');}
 else if(kind==='edit-thread'){const t=findRecord('threads',id);if(!t||!editableRecord('threads',t))return;t.name=get('name');t.subject=get('subject');if(role!=='customer')t.owner=get('owner');}
 else if(kind==='edit-appointment'||kind==='staff-consult'){if(kind==='staff-consult'&&!guard('cro'))return;const a=kind==='edit-appointment'?findRecord('appointments',id):null;if(a&&!editableRecord('appointments',a))return;if(appointments.some(x=>x.id!==id&&x.date===get('date')&&x.time===get('time')&&['Confirmed','Rescheduled'].includes(x.status))){toast('This slot is already booked.');return;}if(a)Object.assign(a,{topic:get('topic'),date:get('date'),time:get('time'),note:get('note')});else appointments.push({id:uid('A'),clientId:get('client'),topic:get('topic'),date:get('date'),time:get('time'),note:get('note'),status:'Confirmed'});}
 else if(kind==='edit-asset'){if(!guard('designer'))return;const [pid,k,index]=id.split('|'),p=visibleProjects().find(p=>p.id===pid),a=(k==='final'?p?.deliverables:p?.prototypes)?.[Number(index)];if(!a)return;if(k==='final')a.note=get('note');else a.caption=get('note');hist(p,'Designer updated asset notes');}
 else done=false;
 if(!done){baseSubmitForm(form,submitter);return;}close();render();toast('Record updated');
};
