const departmentArt={admin:'access',services:'services',marketing:'marketing',quotes:'quotations',finance_quotes:'quotations',designer:'projects',director:'projects',payments:'payments',finance_payments:'payments',communications:'communications',cro:'communications',customer:'customer'};
function dashboardArt(target){const sections={users:'access',permissions:'access',audit:'access',catalogue:'packages',published:'services',quotes:'quotations',accepted:'quotations',projects:'projects',team:'projects',reviews:'projects',invoices:'payments',transactions:'payments',messages:'communications',appointments:'communications',assistant:'customer',cart:'packages'};return 'vivid-'+(sections[target]||departmentArt[role]||'customer')+'-3d.webp';}
/* Reference-inspired dark dashboard presentation. Business actions remain in app.js and lifecycle.js. */
const dashboardNames={admin:'Access overview',services:'Service studio',marketing:'Marketing overview',quotes:'Quotation desk',finance_quotes:'Quotation approvals',designer:'Creative workspace',director:'Project overview',payments:'Payment overview',finance_payments:'Invoice approvals',communications:'Communication hub',cro:'Client relations',customer:'My workspace'};
const dashboardActions={admin:['Create account +','invite'],services:['New offering +','catalognew'],marketing:['Review offerings','go-catalogue'],quotes:['New quotation +','newquote'],finance_quotes:['Review quotations','go-quotes'],designer:['Upload prototype +','assetcreate'],director:['Start a project +','projectcreate'],payments:['Payment request +','newpayment'],finance_payments:['Review invoices','go-invoices'],communications:['New conversation +','newthread'],cro:['Book consultation +','newconsult'],customer:['Build a project brief +','go-catalogue']};
const navIcons={overview:'grid',users:'users',permissions:'shield',audit:'clock',agency:'home',catalogue:'box',published:'check',quotes:'doc',accepted:'check',projects:'pen',team:'users',reviews:'spark',invoices:'card',transactions:'card',outbox:'arrow',messages:'chat',context:'grid',appointments:'calendar',assistant:'spark',cart:'cart',manage:'box'};
let referenceTab='queue';
const countState=(rows,...states)=>rows.filter(r=>states.includes(r.status)).length;
const roundPct=(n,total)=>total?Math.round(n/total*100):0;
const refRow=(title,subtitle,state,action,id,kind='grid',extra='')=>({title,subtitle,state,action,id,kind,extra});
function dashboardModel(){
 const mine=visibleProjects(),myQuotes=quotes.filter(q=>q.clientId===userId),myPayments=paymentRequests.filter(p=>p.clientId===userId),myThreads=threads.filter(t=>t.type==='Client'&&t.clientId===userId);
 const catalogRows=items=>items.map(s=>refRow(s.name,s.kind+' · Version '+s.revision,s.status,'catalogdetail',s.id,s.kind==='Promotion'?'spark':'box',s.kind==='Promotion'?s.discount+'% off':money(s.price)));
 const quoteRows=items=>items.map(q=>refRow(q.title,q.id+' · '+(currentClient(q.clientId).company||currentClient(q.clientId).name),role==='customer'&&!['Sent to client','Accepted','Declined','Requested'].includes(q.status)?'In preparation':q.status,'quotedetail',q.id,'doc',money(role==='customer'&&!['Sent to client','Accepted','Declined'].includes(q.status)?q.estimate??total(q):total(q))));
 const projectRows=items=>items.map(p=>refRow(p.title,p.id+' · Due '+p.due,p.status,'project',p.id,'pen',p.progress+'%'));
 const invoiceRows=items=>items.map(i=>refRow(i.title,i.id+' · V'+i.revision,i.status,'invoice',i.id,'card',money(i.amount)));
 const threadRows=items=>items.map(t=>refRow(t.name,t.type+' · '+t.subject,t.status,'openthread',t.id,'chat',t.messages.length+' messages'));
 const appointmentRows=items=>items.map(a=>refRow(a.topic,a.date+' · '+a.time+' SLST',a.status,role==='cro'?'appointment':'go',role==='cro'?a.id:'appointments','calendar',currentClient(a.clientId).name));
 let d={focus:'',value:0,description:'',unit:'',parts:[],mixTitle:'Workspace balance',mix:[],bars:[],rows:[],view:'manage',queueTitle:'Your work',asideLabel:'Needs attention',asideValue:0,asideMax:1,asideTarget:'manage',asideIcon:'clock',bottomLabel:'Ready to move',bottomValue:0,bottomMax:1,bottomTarget:'manage',note:'',noteAction:'',noteLabel:'',events:[]};
 if(role==='admin'){
  const alive=users.filter(u=>!u.deleted),active=alive.filter(u=>u.active),inactive=alive.filter(u=>!u.active),staff=active.filter(u=>!u.roles.includes('customer'));
  d={...d,focus:'Active accounts',value:active.length,description:'The people behind the studio.',parts:[['Staff',staff.length],['Customers',active.filter(u=>u.roles.includes('customer')).length],['Roles',Object.keys(roles).length]],mixTitle:'Account status',mix:[['Active',active.length],['Suspended',inactive.length]],bars:[['Services',active.filter(u=>u.roles.some(r=>['services','marketing'].includes(r))).length],['Quotes',active.filter(u=>u.roles.some(r=>['quotes','finance_quotes'].includes(r))).length],['Design',active.filter(u=>u.roles.some(r=>['designer','director'].includes(r))).length],['Finance',active.filter(u=>u.roles.some(r=>['payments','finance_payments'].includes(r))).length],['Comms',active.filter(u=>u.roles.some(r=>['communications','cro'].includes(r))).length]],barTitle:'Staff by department',rows:alive.map(u=>refRow(u.name,u.roles.map(r=>roles[r].name).join(' · '),u.active?'Active':'Suspended','edituser',u.id,'users',u.roles.length+' role'+(u.roles.length===1?'':'s'))),view:'users',queueTitle:'People & access',asideLabel:'Suspended accounts',asideValue:inactive.length,asideMax:alive.length,asideTarget:'users',asideIcon:'shield',bottomLabel:'Assigned workspaces',bottomValue:Object.keys(roles).filter(r=>active.some(u=>u.roles.includes(r))).length,bottomMax:Object.keys(roles).length,bottomTarget:'permissions',note:'Give everyone the right access.',noteAction:'invite',noteLabel:'Create an account',events:audit.map(a=>({text:a.text,at:a.at,by:a.role}))};
 }else if(can('services','marketing')){
  const waiting=catalog.filter(s=>s.status==='Pending review'),returned=catalog.filter(s=>s.status==='Changes requested'),live=published(),drafts=catalog.filter(s=>s.status==='Draft');
  d={...d,focus:role==='marketing'?'Awaiting your approval':'Published offerings',value:role==='marketing'?waiting.length:live.length,description:role==='marketing'?'A considered catalogue starts here.':'Your ideas, out in the world.',parts:[['Services',catalog.filter(s=>s.kind==='Service').length],['Packages',catalog.filter(s=>s.kind==='Package').length],['Promotions',catalog.filter(s=>s.kind==='Promotion').length]],mixTitle:'Catalogue status',mix:[['Published',live.length],['In review',waiting.length],['To refine',returned.length],['Drafts',drafts.length]],bars:[['Live',live.length],['Review',waiting.length],['Refine',returned.length],['Draft',drafts.length]],barTitle:'Publishing pipeline',rows:catalogRows([...waiting,...returned,...drafts,...live]),view:'catalogue',queueTitle:role==='marketing'?'Approval queue':'Offering activity',asideLabel:role==='marketing'?'Published offerings':'Marketing review',asideValue:role==='marketing'?live.length:waiting.length,asideMax:catalog.length,asideTarget:role==='marketing'?'published':'catalogue',asideIcon:'box',bottomLabel:role==='marketing'?'Returned for refinement':'Changes requested',bottomValue:returned.length,bottomMax:catalog.length,bottomTarget:'catalogue',note:role==='marketing'?'Only approved work goes live.':'Your next offering starts here.',noteAction:role==='marketing'?'go-catalogue':'catalognew',noteLabel:role==='marketing'?'Review the catalogue':'Create an offering',events:refEvents(catalog)};
 }else if(can('quotes','finance_quotes')){
  const requested=countState(quotes,'Requested','Draft'),review=countState(quotes,'Finance review'),changes=countState(quotes,'Changes requested'),approved=countState(quotes,'Approved'),sent=countState(quotes,'Sent to client'),accepted=countState(quotes,'Accepted');
  d={...d,focus:role==='quotes'?'Briefs to prepare':'Quotations to review',value:role==='quotes'?requested+changes:review,description:role==='quotes'?'Turn the next idea into a clear scope.':'Every commitment, carefully considered.',parts:[['New',requested],['Review',review],['Accepted',accepted]],mixTitle:'Quotation status',mix:[['To prepare',requested+changes],['Finance review',review],['With client',approved+sent],['Accepted',accepted],['Declined',countState(quotes,'Declined')]],bars:[['Brief',requested],['Refine',changes],['Review',review],['Handover',approved+sent],['Accepted',accepted]],barTitle:'Proposal pipeline',rows:quoteRows(role==='finance_quotes'?[...quotes.filter(q=>q.status==='Finance review'),...quotes.filter(q=>q.status!=='Finance review'&&!['Requested','Draft'].includes(q.status))]:quotes),view:'quotes',queueTitle:role==='quotes'?'Quotation activity':'Approval queue',asideLabel:'Accepted quotations',asideValue:accepted,asideMax:quotes.length,asideTarget:role==='quotes'?'accepted':'quotes',asideIcon:'check',bottomLabel:role==='quotes'?'Finance feedback':'Ready for handover',bottomValue:role==='quotes'?changes:approved,bottomMax:quotes.length,bottomTarget:role==='quotes'?'quotes':'outbox',note:role==='quotes'?'The brief is the beginning.':'A clear proposal. A confident client.',noteAction:'go-quotes',noteLabel:role==='quotes'?'Open quotation desk':'Review quotations',events:refEvents(quotes)};
 }else if(can('director','designer')){
  const scope=role==='director'?projects:mine,ready=quotes.filter(q=>q.status==='Accepted'&&!projects.some(p=>p.quoteId===q.id)),active=scope.filter(p=>p.status!=='Completed'),done=countState(scope,'Completed'),review=scope.filter(p=>['Awaiting client review','Director review'].includes(p.prototypes.at(-1)?.status)).length,changes=scope.filter(p=>p.prototypes.at(-1)?.status==='Changes requested').length,available=users.filter(u=>u.active&&u.roles.includes('designer')&&assignedLoad(u.id)<(u.capacity||2)).length;
  d={...d,focus:role==='director'?'Active projects':'My active projects',value:active.length,description:role==='director'?'Good ideas, moving in the right direction.':'A little closer to your next great work.',parts:[['Planning',countState(scope,'Planning')],['In motion',active.length-countState(scope,'Planning')],['Complete',done]],mixTitle:'Project balance',mix:[['In progress',scope.filter(p=>!['Completed','Client review','Planning'].includes(p.status)).length],['Planning',countState(scope,'Planning')],['Client review',countState(scope,'Client review')],['Completed',done]],bars:[['Planning',countState(scope,'Planning')],['Design',countState(scope,'In progress')],['Review',countState(scope,'Client review')],['Final',countState(scope,'Final design')],['Done',done]],barTitle:'Projects by stage',rows:[...(role==='director'?ready.map(q=>refRow(q.title,q.id+' · Accepted quotation','Ready to start','startproject',q.id,'doc',money(total(q)))):[]),...projectRows(scope)],view:'projects',queueTitle:role==='director'?'Project activity':'My project activity',asideLabel:role==='director'?'Available designers':'Awaiting feedback',asideValue:role==='director'?available:review,asideMax:role==='director'?users.filter(u=>u.active&&u.roles.includes('designer')).length:scope.length,asideTarget:role==='director'?'team':'reviews',asideIcon:role==='director'?'users':'chat',bottomLabel:role==='director'?'Ready to start':'Revisions to make',bottomValue:role==='director'?ready.length:changes,bottomMax:role==='director'?quotes.length:scope.length,bottomTarget:role==='director'?'projects':'reviews',note:role==='director'?'The right team makes the difference.':'Give your next idea a first look.',noteAction:role==='director'?'go-team':'assetcreate',noteLabel:role==='director'?'View designer availability':'Share a prototype',events:refEvents(scope)};
 }else if(can('payments','finance_payments')){
  const succeeded=transactions.filter(t=>t.status==='Succeeded'),sum=succeeded.reduce((s,t)=>s+t.amount,0),review=countState(invoices,'Finance review'),changes=countState(invoices,'Changes requested'),approved=countState(invoices,'Approved'),sent=countState(invoices,'Sent to client');
  d={...d,focus:role==='payments'?'Verified payments':'Invoices to review',value:role==='payments'?money(sum):review,description:role==='payments'?'Every payment, kept in balance.':'The final check before client delivery.',parts:[['Review',review],['Corrections',changes],['Delivered',sent]],mixTitle:'Invoice status',mix:[['Finance review',review],['Corrections',changes],['Approved',approved],['Delivered',sent]],bars:[['Unpaid',countState(paymentRequests,'Unpaid')],['Review',review],['Correct',changes],['Approved',approved],['Sent',sent]],barTitle:'Payment & invoice flow',rows:invoiceRows([...invoices.filter(i=>i.status===(role==='payments'?'Changes requested':'Finance review')),...invoices.filter(i=>i.status!==(role==='payments'?'Changes requested':'Finance review'))]),view:'invoices',queueTitle:role==='payments'?'Invoice activity':'Invoice approval queue',asideLabel:role==='payments'?'Correction requests':'Ready to send',asideValue:role==='payments'?changes:approved,asideMax:invoices.length,asideTarget:role==='payments'?'invoices':'outbox',asideIcon:role==='payments'?'doc':'arrow',bottomLabel:'Delivered invoices',bottomValue:sent,bottomMax:invoices.length,bottomTarget:role==='payments'?'invoices':'outbox',note:role==='payments'?'A clear record, from start to finish.':'Approval unlocks the next step.',noteAction:role==='payments'?'go-transactions':'go-invoices',noteLabel:role==='payments'?'Open transaction ledger':'Review invoice details',events:refEvents(invoices)};
 }else if(can('communications','cro')){
  const open=countState(threads,'Open'),resolved=countState(threads,'Resolved'),requested=countState(appointments,'Requested'),confirmed=countState(appointments,'Confirmed','Rescheduled');
  d={...d,focus:role==='cro'?'Consultation requests':'Open conversations',value:role==='cro'?requested:open,description:role==='cro'?'Make room for a good conversation.':'Every conversation, connected.',parts:[['Client',threads.filter(t=>t.type==='Client').length],['Internal',threads.filter(t=>t.type==='Internal').length],['Resolved',resolved]],mixTitle:role==='cro'?'Consultation status':'Inbox balance',mix:role==='cro'?[['Requested',requested],['Confirmed',confirmed],['Completed',countState(appointments,'Completed')],['Cancelled',countState(appointments,'Cancelled')]]:[['Client · open',threads.filter(t=>t.type==='Client'&&t.status==='Open').length],['Internal · open',threads.filter(t=>t.type==='Internal'&&t.status==='Open').length],['Resolved',resolved]],bars:[['Client',threads.filter(t=>t.type==='Client').length],['Internal',threads.filter(t=>t.type==='Internal').length],['Booked',confirmed],['Requests',requested],['Resolved',resolved]],barTitle:'Communication snapshot',rows:role==='cro'?[...appointmentRows(appointments),...threadRows(threads)]:threadRows(threads),view:role==='cro'?'appointments':'messages',queueTitle:role==='cro'?'Client activity':'Conversation activity',asideLabel:role==='cro'?'Open conversations':'Consultation requests',asideValue:role==='cro'?open:requested,asideMax:role==='cro'?threads.length:appointments.length,asideTarget:role==='cro'?'messages':'context',asideIcon:'chat',bottomLabel:role==='cro'?'Confirmed consultations':'Resolved conversations',bottomValue:role==='cro'?confirmed:resolved,bottomMax:role==='cro'?appointments.length:threads.length,bottomTarget:role==='cro'?'appointments':'messages',note:role==='cro'?'Make every client feel understood.':'Context makes conversations better.',noteAction:role==='cro'?'go-appointments':'go-context',noteLabel:role==='cro'?'Manage consultations':'View company context',events:threads.flatMap(t=>t.messages.map(m=>({text:m.text,at:m.at,by:t.type+' · '+t.name})))};
 }else{
  const unpaid=myPayments.filter(p=>p.status==='Unpaid'),due=unpaid.reduce((s,p)=>s+p.amount,0),review=mine.filter(p=>p.prototypes.at(-1)?.status==='Awaiting client review'),qReview=myQuotes.filter(q=>q.status==='Sent to client'),done=countState(mine,'Completed');
  d={...d,focus:'My active projects',value:mine.filter(p=>p.status!=='Completed').length,description:'Your next big thing, taking shape.',parts:[['Quotations',myQuotes.length],['Projects',mine.length],['Complete',done]],mixTitle:'My project balance',mix:[['In progress',mine.filter(p=>!['Completed','Client review','Planning'].includes(p.status)).length],['Planning',countState(mine,'Planning')],['For review',countState(mine,'Client review')],['Completed',done]],bars:[['Briefs',countState(myQuotes,'Requested','Draft')],['Quotes',qReview.length],['Design',mine.filter(p=>p.status!=='Completed').length],['Review',review.length],['Done',done]],barTitle:'Your creative journey',rows:[...quoteRows(qReview),...projectRows(review),...unpaid.map(p=>refRow(p.title,p.id+' · Project payment','Unpaid','checkout',p.id,'card',money(p.amount))),...projectRows(mine.filter(p=>!review.includes(p)))],view:'projects',queueTitle:'Your project activity',asideLabel:'Outstanding balance',asideValue:money(due),asideMax:0,asideTarget:'invoices',asideIcon:'card',bottomLabel:'Decisions waiting',bottomValue:qReview.length+review.length,bottomMax:myQuotes.length+mine.length,bottomTarget:qReview.length?'quotes':'projects',note:'A little help, whenever you need it.',noteAction:'go-assistant',noteLabel:'Ask the studio assistant',events:[...refEvents(mine),...myThreads.flatMap(t=>t.messages.filter(m=>!m.customer).map(m=>({text:m.text,at:m.at,by:'Your studio team'})))]};
 }
 return d;
}
function refEvents(records){return records.flatMap(r=>(r.history||[]).map(h=>({text:typeof h==='string'?h:h.text,at:h.at||'',by:r.title||r.name||r.id}))).reverse();}
function chartAria(groups){return groups.map(([label,n])=>label+': '+n).join(', ');}
const ringColors=['#ff846f','#ed5b9c','#e1c280','#8d8bca','#96b6b0'];
function refDonut(d){const total=d.mix.reduce((s,x)=>s+x[1],0);let offset=0;const arcs=d.mix.map(([label,n],i)=>{const len=total?n/total*100:0;const value=`<circle cx="64" cy="64" r="51" pathLength="100" fill="none" stroke="${ringColors[i%ringColors.length]}" stroke-width="8" stroke-dasharray="${len} ${100-len}" stroke-dashoffset="${-offset}" transform="rotate(-90 64 64)"/>`;offset+=len;return value;}).join('');return `<section class="ref-card ref-donut-card"><div class="ref-card-header"><h2>${d.mixTitle}</h2><button class="ref-more" data-act="go" data-id="${d.view}" aria-label="Open ${esc(d.mixTitle)}">···</button></div><div class="ref-donut-body"><div class="ref-donut-info"><strong>${total.toString().padStart(2,'0')}</strong><span>Total ${can('admin')?'accounts':can('services','marketing')?'offerings':can('quotes','finance_quotes')?'quotations':can('payments','finance_payments')?'invoices':role==='cro'?'consultations':role==='communications'?'conversations':'projects'}</span><div class="ref-legend">${d.mix.filter(x=>x[1]>0).map(([label,n])=>`<div><i style="background:${ringColors[d.mix.findIndex(x=>x[0]===label)%ringColors.length]}"></i><span>${label}</span><b>${n}</b></div>`).join('')||'<p>No records yet</p>'}</div></div><div class="ref-ring"><svg viewBox="0 0 128 128" role="img" aria-label="${esc(chartAria(d.mix))}"><circle cx="64" cy="64" r="51" fill="none" stroke="#35343e" stroke-width="8"/>${arcs}</svg><span class="workspace-3d"><img src="${dashboardArt()}" alt="" width="96" height="96"></span></div></div></section>`;}
function refFocus(d){return `<section class="ref-focus-card"><div class="ref-card-header"><h2>${d.focus}</h2><button class="ref-more" data-act="go" data-id="${d.view}" aria-label="Open ${esc(d.focus)}">···</button></div><strong class="ref-focus-value ${String(d.value).length>8?'wide-value':''}">${typeof d.value==='number'?d.value.toString().padStart(2,'0'):d.value}</strong><p>${d.description}</p><div class="ref-focus-art" aria-hidden="true"><img src="${dashboardArt()}" alt="" width="180" height="180"></div><div class="ref-focus-parts">${d.parts.map(([label,n])=>`<div><span>${label}</span><strong>${n.toString().padStart(2,'0')}</strong></div>`).join('')}</div></section>`;}
function refMini(label,value,iconName,target,maximum,tone='pink'){const progress=typeof value==='number'&&maximum?Math.min(100,roundPct(value,maximum)):0;return `<button class="ref-mini ref-card" data-act="go" data-id="${target}"><span class="ref-mini-badge ${tone}"><img src="${dashboardArt(target)}" alt="" width="68" height="68"></span><div><span>${label}</span><strong>${value}</strong>${maximum?`<span class="ref-mini-track"><i style="width:${progress}%"></i></span>`:''}</div><span class="ref-mini-arrow">↗</span></button>`;}
function refStageChart(d){const max=Math.max(...d.bars.map(x=>x[1]),1);return `<section class="ref-card ref-stage-card"><div class="ref-card-header"><h2>${d.barTitle}</h2><button class="ref-more" data-act="go" data-id="${d.view}" aria-label="Open ${esc(d.barTitle)}">···</button></div><span class="ref-chart-caption">Current counts · by category</span><div class="ref-stage-chart" role="img" aria-label="${esc(chartAria(d.bars))}">${d.bars.map(([label,n],i)=>`<div class="ref-stage-column"><div class="ref-stage-track"><span class="ref-stage-number">${n}</span><div class="ref-stage-bar ${n===max&&n>0?'highlight':''}" style="height:${n/max*100}%;${n===0?'min-height:3px;':''}"></div></div><span>${label}</span></div>`).join('')}</div><div class="ref-chart-footer"><span class="ref-footer-icon">${icon('check')}</span><span>Workspace snapshot</span><strong>${d.mix.reduce((s,x)=>s+x[1],0).toString().padStart(2,'0')}</strong></div></section>`;}
function refWorkTable(d){return `<section class="ref-work-panel"><div class="ref-work-tabs" role="tablist" aria-label="Dashboard activity"><button class="${referenceTab==='queue'?'selected':''}" role="tab" aria-selected="${referenceTab==='queue'}" data-act="reftab" data-id="queue">${d.queueTitle}</button><button class="${referenceTab==='activity'?'selected':''}" role="tab" aria-selected="${referenceTab==='activity'}" data-act="reftab" data-id="activity">Recent activity</button>${smallbutton('View all ↗','go',d.view)}</div><div role="tabpanel" class="ref-work-list">${referenceTab==='queue'?(d.rows.length?d.rows.slice(0,6).map((row,i)=>`<div class="ref-work-row"><span class="ref-row-icon tone-${i%4}">${icon(row.kind)}</span><button class="ref-row-title" data-act="${row.action}" data-id="${esc(row.id)}"><strong>${esc(row.title)}</strong><small>${esc(row.subtitle)}</small></button><span class="ref-row-extra">${esc(row.extra)}</span>${status(row.state)}<button class="ref-row-open" data-act="${row.action}" data-id="${esc(row.id)}" aria-label="Open ${esc(row.title)}">↗</button></div>`).join(''):empty('You’re all caught up.','Your next task will appear here.')):(d.events.length?d.events.slice(0,6).map((e,i)=>`<div class="ref-work-row activity-row"><span class="ref-row-icon tone-${i%4}">${icon('clock')}</span><div class="ref-row-title"><strong>${esc(e.text)}</strong><small>${esc(e.by)}</small></div><time>${esc(e.at||'Earlier')}</time></div>`).join(''):empty('A fresh start.','Changes in your workspace will appear here.'))}</div></section>`;}
overview=function(){const d=dashboardModel(),action=dashboardActions[role];return `<div class="ref-welcome"><div><span>Welcome back, ${esc(me().name.split(' ')[0])} <span class="ref-welcome-spark">✳</span></span><p>${esc(roles[role].sub)}</p></div><span class="ref-current-label">${icon('clock')} Current workspace</span></div><div class="ref-layout"><div class="ref-main-column"><div class="ref-top-cards">${refFocus(d)}${refDonut(d)}</div>${refWorkTable(d)}<div class="ref-context-footer"><span class="ref-small-avatar">${initial(me().name)}</span><div><strong>${esc(roles[role].name)}</strong><span>${esc(roles[role].dept)} · ${esc(me().email)}</span></div>${button('Manage records','go','manage')}</div></div><aside class="ref-right-column">${refMini(d.asideLabel,d.asideValue,d.asideIcon,d.asideTarget,d.asideMax)}${refStageChart(d)}${refMini(d.bottomLabel,d.bottomValue,'check',d.bottomTarget,d.bottomMax,'peach')}<section class="ref-next-card"><span class="ref-next-label">YOUR NEXT STEP</span><h2>${d.note}</h2>${button(d.noteLabel+' ↗',d.noteAction)}</section></aside></div>`;};
render=function(){if(publicView){landing();return;}window.AxiomHero3D?.dispose();if(!roles[role].pages.some(x=>x[0]===page))page='overview';const r=roles[role],a=dashboardActions[role];$('#app').innerHTML=`<div class="app-shell reference-shell" data-department="${departmentArt[role]}"><aside class="sidebar reference-sidebar"><button class="ref-logo" data-act="home" aria-label="AXIOM studio home" title="AXIOM studio home">${icon('spark')}</button><nav aria-label="${esc(r.name)} navigation">${r.pages.map(([id,label])=>`<button class="navitem ${page===id?'active':''}" data-act="go" data-id="${id}" aria-label="${esc(label)}" aria-current="${page===id?'page':'false'}" title="${esc(label)}">${icon(navIcons[id]||'grid')}<span>${label}</span></button>`).join('')}</nav><div class="ref-rail-footer"><button class="navitem" data-act="switch" title="Switch workspace" aria-label="Switch workspace">${icon('users')}<span>Switch workspace</span></button><button class="avatar" data-act="profile" title="${esc(me().name)}" aria-label="Your profile">${initial(me().name)}</button><button class="navitem" data-act="home" aria-label="Back to studio website" title="Back to studio website">${icon('home')}<span>Studio website</span></button></div></aside><main class="main"><header class="appbar reference-appbar"><div class="ref-title-group"><h1>${esc(page==='overview'?dashboardNames[role]:r.pages.find(x=>x[0]===page)?.[1])}</h1><button class="ref-workspace-chip" data-act="switch" aria-label="Switch workspace: ${esc(r.name)}"><span class="ref-workspace-dot">${icon(r.icon)}</span><span>${esc(r.name)}</span><b>⌄</b></button></div><div class="right">${page==='overview'?button(a[0],a[1],'','ref-header-action'):button('Switch workspace','switch','','ref-header-action')}<button class="iconbtn ref-notification" data-act="notifications" aria-label="Notifications">${icon('bell')}</button></div></header><div class="content">${page==='overview'?overview():pageView()}<footer class="appfooter"><span>AXIOM STUDIO <i>/</i> ${esc(r.dept)}</span><span>Interactive demo · Changes reset on reload · No real charges</span></footer></div></main></div>`;};
const referenceAct=act;
act=function(action,id=''){if(action==='reftab'){referenceTab=id==='activity'?'activity':'queue';render();return;}if(['enter','switch','home'].includes(action))referenceTab='queue';referenceAct(action,id);};
readRoute();
